language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python tests.py
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: htmltopdfapi
  on:
    repo: mariusavram91/htmltopdf

